name: staging-deploy

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Deployment
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello
      run : echo "hello world"
