name: staging-deploy
env:
  APPLICATION_NAME: "MyActions"
  PACKAGE_NAME: "deploy"

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Deployment
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello
      run : echo "hello world"

    - name: Execute commands
      run : |
        echo "hello world2"
        echo "hello world3"
